# Generated by Django 6.0.5 on 2026-05-08 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField(help_text='Prompt passed to `claude -p <prompt>`.')),
                ('working_dir', models.CharField(help_text='Absolute path. claude runs in this cwd.', max_length=1024)),
                ('extra_args', models.TextField(blank=True, default='', help_text='Extra CLI args appended to claude. One arg per line OR shell-quoted single line.')),
                ('model', models.CharField(blank=True, default='sonnet', max_length=120)),
                ('permission_mode', models.CharField(blank=True, default='', max_length=40)),
                ('allowed_tools', models.CharField(blank=True, default='', max_length=500)),
                ('disallowed_tools', models.CharField(blank=True, default='', max_length=500)),
                ('add_dirs', models.TextField(blank=True, default='', help_text='One absolute path per line.')),
                ('output_format', models.CharField(blank=True, default='stream-json', help_text='text, json, stream-json. Use stream-json for live UI streaming.', max_length=20)),
                ('dangerously_skip_permissions', models.BooleanField(default=False)),
                ('verbose', models.BooleanField(default=False)),
                ('max_budget_usd', models.CharField(blank=True, default='', max_length=20)),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual only'), ('interval', 'Interval'), ('cron', 'Cron')], default='manual', max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cron_expr', models.CharField(blank=True, default='', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('trigger', models.CharField(default='manual', help_text='manual | scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('argv_json', models.TextField(blank=True, default='[]')),
                ('log_path', models.CharField(blank=True, default='', max_length=512)),
                ('auth_required', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
